### ISSUE TITLE
access to VSDFullBody database

### ISSUE THREAD

**Issue by modenaxe** [RWTHmediTEC/VSDFullBodyBoneModels#1]
Hello,
more than an issue this is a question. I have seen in few of your repositories this sentence:

>The original segmentations and reconstructions can be found as MHA files in the VSDFullBody database hosted at www.smir.ch.

but the database does not seem to be accessible and/or any reference contact working. I am not sure if you are affiliated with smir.ch, but would you be able to provide any advice on how to access that database?

Thank you,

Luca

**Comment by MCM-Fischer** [comment]
Hi Luca

I'm not affiliated with smir.ch. I'm only a user of the website.
As far as I remember they have to create a research unit for your institute in the first place. Then you can register at https://www.smir.ch/Account/Register and select your research unit. 

Did you try the following email address: support [at] smir [dot] ch ?

Kind regards
Max

**Comment by modenaxe** [comment]
Hi Max,

Thank you for the prompt reply! Actually I have tried registering several time, emailing support at smir [dot] ch and even emailing contact [at] si-cas.com and the first author of the Virtual Skeleton Database. Did you register before the end of 2018 by any chance? That's when I tried the first time. Maybe the website is not supported anymore....

Luca

**Comment by MCM-Fischer** [comment]
Yes, I registered in 2017. I will send you an email.
