### ISSUE TITLE
How can I get the  VSDFullBody database 

### ISSUE THREAD

**Issue by EllenWang1999** [RWTHmediTEC/VSDFullBodyBoneModels#2]
Hello,
I ran into some questions when trying to get the pelvis datasets.
It seems to be nor accessible.(https://www.smir.ch/)
Can you send the dataset to me? My email is 1114199031@qq.com
Thank you so much!
Ellen

**Comment by MCM-Fischer** [comment]
Hi Ellen

A re-upload can be found via: https://doi.org/10.1038/s41597-023-02669-z

Kind regards
